name: Generate HSN Animation

on:
  # Automatically run every 24 hours
  schedule:
    - cron: "0 0 * * *"  # Adjust the schedule as needed
  
  # Manually trigger the workflow
  workflow_dispatch:
  
  # Run on every push to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Generate the SVG with HSN pattern
      - name: Generate HSN Contribution Grid Snake
        run: |
          curl -sL https://github.com/Platane/snk/releases/download/v3/svg-only@v3.tar.gz | tar xz
          ./generate-snake.sh --user ${{ github.repository_owner }} --pattern "HSN" --output dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Push the generated SVG to a branch
      - name: Push HSN SVG to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
