name: timing-auto-push-latest-blog-post # 定时推送指定平台博客信息到主页
on:
  schedule:
    # 定时器配置 0 * * * * 每小时推送一次
    - cron: "0 0/12 * * *" # 0/5 * * * * 每5分钟推送一次
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10" # 获取链接数量
          feed_list: "http://blog.holic-x.com/atom.xml" # 博客订阅地址(RSS格式/Atom格式),以逗号间隔不同的地址
