name: WakaTime Readme # 统计提交代码所使用的的语言并推送到首页（对应不同IDE编码统计）

on:
  push:
    branches:
      - main # 分支
  schedule:
    - cron: '0 19 * * *' # 定时器配置 0 19 * * *

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # waka个人秘钥
          SHOW_TITLE: true # 统计一周数据
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿ # 图形风格